### ISSUE TITLE
Zijn HOOFDLETTERS hier een stukje inhoud, of styling?

### ISSUE THREAD

**Issue by krijnhoetmer** [Daniquedejong/the-web-is-for-everyone-interactive-functionality#1]
https://github.com/Daniquedejong/the-web-is-for-everyone-interactive-functionality/blob/6629474e9743d938cfc096ec4b550165538db57c/views/partials/head.ejs#L13

**Comment by Daniquedejong** [comment]
Ik heb nu met "text-transform: uppercase" de hoofdletters gestyled!
